DAPSCoin/DAPSCoin

- src/main.cpp
- src/main.h
- src/qt/dapscoin.cpp
- src/qt/walletframe.cpp
- src/txdb.cpp
- src/util.h
Various upstream fixes:
[Refactor] Remove unused setStakeSeen - variable https://github.com/PIVX-Project/PIVX/pull/890
[UI] Fix improperly parented walletView and segmentation fault on QT 5.10 - https://github.com/PIVX-Project/PIVX/pull/900
[Log] Handle errors during log message formatting - https://github.com/PIVX-Project/PIVX/pull/903
[UI] Fix AA_EnableHighDpiScaling warning - https://github.com/PIVX-Project/PIVX/pull/1057
> Various Fixes from Upstream

- src/rpc/masternode.cpp
- src/rpc/server.cpp
- src/rpc/server.h
Restore old masternodes command to avoid confusion
> Restore Old Masternode commands

- src/qt/bitcoingui.cpp
- src/qt/overviewpage.cpp
- src/wallet/rpcwallet.cpp
- src/wallet/wallet.cpp
- Fix Spendable showing Locked coins
- Add locked, immature to getbalances RPC
Minor addition:
Add F2 Shortcut to open DAPSCoin folder
> Fix Spendable showing Locked coins

- src/netbase.cpp
- src/qt/bitcoingui.cpp
- src/qt/bitcoingui.h
- src/qt/guiconstants.h
- src/qt/historypage.cpp
- src/qt/optionspage.cpp
- src/qt/sendcoinsdialog.cpp
- src/qt/splashscreen.cpp
- Fix alignment in History table
- Add Frequently Asked Questions to Help menu
- Adjust Disable Reserve Balance button
- Hide Coin Control Frame until fully implemented
- Move excessive "Socket close failed" log behind net category
- Minor splash screen adjustments
- Use 1 second GUI update time (from 250ms)
> Various Updates for next Beta

- share/qt/Info.plist.in
- src/httpserver.cpp
- src/httpserver.h
- src/kernel.cpp
- src/main.cpp
- src/qt/transactiontablemodel.cpp
- src/wallet/wallet.cpp
- Update minimum MacOS to 10.10 (was missed previously when Depends were updated)
- [Startup][GUI][Performance] Optimizations for huge wallets. https://github.com/PIVX-Project/PIVX/pull/1217
- Delete __init__.py
- Update logging in main.cpp
- Remove Boost dependency from the httpserver -https://github.com/Fuzzbawls/PIVX/commit/19ac6d8f1bab07b9d506ffb3ca8bbaa54ab6e2d1
- Missed line breaks in failed to load spend/view key logging
> Final Touches for v1.0.5 release [Work in Progress]

- src/miner.cpp
- src/qt/optionspage.cpp
- src/qt/res/css/Dark.css
- src/qt/res/css/Light.css
- src/wallet/wallet.cpp
> Minor UI Fixes

- src/crypter.cpp
- src/crypter.h
- src/init.cpp
- src/qt/transactionrecord.cpp
- src/qt/transactionrecord.h
- src/qt/transactiontablemodel.cpp
- src/wallet/wallet.cpp
- src/wallet/wallet.h
- src/wallet/walletdb.cpp
- src/wallet/walletdb.h
[Wallet][Startup][DB][Backport] Remove vchDefaultKey from wallet.h - https://github.com/PIVX-Project/PIVX/pull/1030
[Model][Backport] Remove mapWallet not needed call + stop treating coinbase differently - https://github.com/PIVX-Project/PIVX/pull/1073
[Wallet] Graceful shutdown in the unlock corrupted wallet. - https://github.com/PIVX-Project/PIVX/pull/1229
> Last Few Upstream for v1.0.5

- src/dapscoin-cli.cpp
- src/dapscoin-tx.cpp
- src/dapscoind.cpp
Add more output when launching daemon (version, masternode=1 or not)
Update other minor texts
> Minor Daemon/CLI/TX Utility fixes/additions

- src/qt/transactiontablemodel.cpp
fix from https://github.com/PIVX-Project/PIVX/pull/1267
> [Upstream Fix][Qt][Bug] Load the most recent instead of the first transactions

- depends/packages/qt.mk
QT Updated to 5.9.9 in December. This will likely be the last 5.9.* release according to https://www.qt.io/blog/qt-5.9.9-released
> Update QT to 5.9.9 LTS

- src/qt/forms/optionspage.ui
- src/qt/optionspage.cpp
- src/qt/optionspage.h
> Add UPNP checkbox to Settings page

- src/chainparams.cpp
Update checkpoints every 5k from 240000 to 260000
> Update checkpoints every 5k from 240000 to 260000

- src/chainparams.cpp
- src/qt/addresstablemodel.cpp
- src/qt/bitcoingui.cpp
- src/qt/bitcoingui.h
- src/qt/historypage.cpp
- src/qt/res/css/Dark.css
- src/qt/res/css/Light.css
- src/qt/transactiontablemodel.cpp
- src/wallet/wallet.cpp
- Remove setWindowless from History Page ComboBoxes
(fixes this 
- Update duplicate syncTime
- Updated logging
- Add Block Count under Network Status
- Add checkpoint for 265000
> Minor Fixes/Updates

- src/qt/bitcoingui.cpp
- src/qt/forms/overviewpage.ui
- src/qt/overviewpage.cpp
- src/qt/overviewpage.h
- Use NUM_ITEMS variable in Overview
- Switch to signal based showBlockCurrentHeight function vs QTimer (This allows for more accurate display of Blocks on Overview screen)
- Restore tooltip for Block Count
- Update createMenuBar - add CSS name / cleanup unused code
- Cleanup jumbled pingNetworkInterval code
> Minor Fixes

- src/main.cpp
- Ban/Disconnect from v1.0.3.4 or lower
> Ban/Disconnect Older Versions (v1.0.3.4 or lower)

- src/qt/bitcoingui.cpp
- src/sync.h
Add WITH_LOCK macro: run code while locking a mutex. - https://github.com/PIVX-Project/PIVX/pull/1325
[GUI] Open the app's window in the smallest, currently available, size. - https://github.com/PIVX-Project/PIVX/pull/1266
> Recent Upstream Updates

- src/init.cpp
- src/main.cpp
> Upstream@[8392](https://github.com/bitcoin/bitcoin/pull/8392) backport.
https://github.com/PIVX-Project/PIVX/pull/1333
> [Upstream][Backport] Wait locking for genesis connection.

- src/main.cpp
- src/main.h
- src/qt/walletmodel.cpp
> auto-descriptive title.
> 
> An increased delay time between GUI polling updates when reindex/import is being executed.
from https://github.com/PIVX-Project/PIVX/pull/1332
> [Upstream][GUI] Do not update the GUI so often when reindex/import is being executed. 

- src/wallet/wallet.cpp
- src/wallet/wallet.h
No functional changes here, just moving wallet functions out of the header file into the source file
reference: https://github.com/PIVX-Project/PIVX/pull/970/commits/47345be6055edb1a24909a221d36c67fa978d299
> [Refactor] Move wallet functions out of header

- src/chainparams.cpp
> Fix extra comma in chainparams

- src/net.cpp
> Minor updates to how the banlist is handled. ported from [bitcoin#7350](https://github.com/bitcoin/bitcoin/pull/7350)
from https://github.com/PIVX-Project/PIVX/pull/1363
> [Upstream] [Net] Banlist updates

- src/dapscoind.cpp
- src/init.cpp
- src/init.h
- src/qt/dapscoin.cpp
> Backport of [bitcoin#6780](https://github.com/bitcoin/bitcoin/pull/6780)
> 
> Currently optionsModel(QT) parameters interaction overwrites/dominates initial and depending parameter settings. This PR would factor out init's parameter interaction and call it before AppInit2().
from https://github.com/PIVX-Project/PIVX/pull/1375
> [Upstream][Init] Do parameter interaction before creating the UI model

- src/crypter.h
- src/init.cpp
- src/wallet/wallet.cpp
- src/wallet/wallet.h
- src/wallet/walletdb.cpp
- src/wallet/walletdb.h
https://github.com/DAPSCoin/DAPSCoin/commit/6b911fdc90e40384c198125a515a30076ac7dcc9
The commit above caused an issue with passphrases in the daemon. Revert it for now.
> [RPC][Daemon] Fix passphrase issue

- src/rpc/rawtransaction.cpp
Removes the decoding of decoys that are not specific to this tx.
Closes #124
> Issue #124

- src/qt/bitcoingui.cpp
with min resolution 1147x720 
with min resolution 600x800
> Fix size to low resolution

- src/key.cpp
> Restore fValid Assertion

- src/main.cpp
- src/poa.cpp
> Fix Accepted PoA Block Failed

- src/base58.cpp
- src/base58.h
- src/main.cpp
> Coming from:
> 
> * [bitcoin#6468](https://github.com/bitcoin/bitcoin/pull/6468) .
> * [bitcoin#7656](https://github.com/bitcoin/bitcoin/pull/7656) .
> * [bitcoin#7922](https://github.com/bitcoin/bitcoin/pull/7922)
> * [bitcoin#8736](https://github.com/bitcoin/bitcoin/pull/8736) .
> * [bitcoin#10961](https://github.com/bitcoin/bitcoin/pull/10961) .
from https://github.com/PIVX-Project/PIVX/pull/1676
> [Upstream] [Backport] Base58 performance improvements

- src/wallet/wallet.cpp
This should fix the fValid error at startup that some users were experiencing
> Fix for fValid error at startup

- src/main.cpp
Ban previous versions up to and including 1.0.5.8
> Ban previous versions up to and including 1.0.5.8

- src/qt/bitcoingui.cpp
> Fix Medium link

- contrib/dapscoin-qt.desktop
- contrib/dapscoin-qt.pro
- src/qt/bitcoingui.cpp
- src/qt/bitcoingui.h
- Update dapscoin-qt.pro with missing files
- Update bootstrap link
- Add GitHub Wiki link
- Add default .desktop file for creation of AppImage
> [Trivial] Minor Updates

- src/rpc/misc.cpp
- src/rpc/server.cpp
This one should help solve the Explorer daemon crash due to commands being called at startup
from https://github.com/PIVX-Project/PIVX/pull/1909
> [Upstream][Bug][RPC] Guard RPC server during warm-up

- src/qt/2faconfirmdialog.cpp
- src/qt/2fadialog.cpp
- src/qt/2faqrdialog.cpp
- src/qt/forms/2faconfirmdialog.ui
- src/qt/forms/2fadialog.ui
- src/qt/forms/optionspage.ui
- src/qt/optionsmodel.cpp
- src/qt/optionspage.cpp
- src/qt/optionspage.h
- src/qt/qgoogleauth.cpp
- src/qt/res/css/Dark.css
[2FA] Add 2FA digits settings/options (6 or 8) [default to 6]
> [2FA] Add 2FA digits settings/options (6 or 8)

- src/chainparams.cpp
Update Fix Date to December 12
> Update Fix Date to December 12

- src/chainparams.cpp
To better align with exchanges and partners
Tuesday, December 29, 2020 12:00:00 AM
> Update Fix Date to December 29

- src/chainparams.cpp
- src/chainparams.h
- src/net.cpp
- src/poa.cpp
No longer required after Dec 29, this removes the time check.
> Remove PoAFixTime()

- src/chainparams.cpp
> Remove dead/unused Seed Nodes

- src/chainparams.cpp
Adding vps.dapscoin.com - vps5.dapscoin.com to potentially help with connection issues
> Add additional seeds based on VPS

- .github/workflows/daps-build-factory.yml
- depends/packages/qt.mk
- Depends: QT - Use temporary link for building
- Rename GitHub Actions artifacts
> [Build] Build Updates

- src/chainparams.cpp
> Remove dapscoin-seeds.com seed nodes
