DAPSCoin/DAPSCoin

- src/qt/bitcoingui.cpp
- src/qt/bitcoingui.h
- src/qt/coincontroldialog.cpp
- src/qt/coincontroldialog.h
- src/qt/coincontroltreewidget.cpp
- src/qt/forms/coincontroldialog.ui
- src/qt/forms/unlockdialog.ui
Add History, Masternodes, Settings to Tray/Dock icon menu
Add "not responding" message to Unlock Dialog
Upstream:
[UI] Sort numbers correctly in zPIV and coin control dialogs - https://github.com/PIVX-Project/PIVX/pull/725/files
[GUI] Sort by 'data' in coin control dialog - https://github.com/PIVX-Project/PIVX/pull/741
[GUI] Segfault for a bad cast of the parent in the escape key press event - https://github.com/PIVX-Project/PIVX/pull/1053
> Minor [UI] Updates

- src/activemasternode.cpp
- src/activemasternode.h
- src/init.cpp
- src/kernel.cpp
- src/miner.cpp
- src/qt/bitcoingui.cpp
- src/qt/coincontroldialog.cpp
- src/qt/overviewpage.cpp
- src/rpc/masternode.cpp
- src/rpc/rawtransaction.cpp
- src/test/wallet_tests.cpp
- src/wallet/test/wallet_tests.cpp
- src/wallet/wallet.cpp
- Add "No Active Peers"/"Syncing..." status' to setStakingStatus (visual staking status)
->Different from !masternodeSync.IsSynced() - Syncing will check for IsInitialBlockDownload
- Move reserveBalance within #ifdef ENABLE_WALLET (requires wallet)
- Remove excessive logs re: staking/nTime violations
- Remove unnecessary check in Miner
- Restore sleep timer in miner with setting in conf file 'minersleep', 30sec default
- Change timerBlockHeightLabel from 45s->60s (60s block times anyway)
> Various Minor Updates

- src/qt/bitcoingui.cpp
- src/qt/forms/optionspage.ui
- src/qt/optionspage.cpp
- src/qt/splashscreen.cpp
Add a basic Lite Mode (litemode=1) 
This hides the masternode tab and disables staking (button and function) for a "Lite" wallet.
This will be expanded on in the future.
> Add Basic Litemode

- src/wallet/wallet.cpp
Tested and working so far within test group. Overly commented for easy reading for now, can be cleaned up in next version
Additional notes:
We don't use SwitftX, that if statement removed as well as two obfuscation related errors that no user would see. Also, fixed incorrect error about 50UTXOS and replaced with more correct generic error.
> Potential fix for incorrect reserve balance error when trying to send

- src/qt/bitcoingui.cpp
- src/qt/dapscoin.cpp
- src/qt/overviewpage.cpp
- src/qt/walletview.cpp
- Fix "Staking" word randomly stuck in the file menu
- Fix "Enabling Staking" still displaying on Overview
- Disable staking icon timer
- Force WriteStakingStatus(false) after unlock to disable staking
- Remove extra log in overviewpage.cpp
> Fixes for Lite Mode

- src/qt/forms/optionspage.ui
- src/qt/optionspage.cpp
- src/qt/optionspage.h
- src/qt/res/css/Dark.css
- src/qt/res/css/Light.css
- src/qt/transactiontablemodel.cpp
- Add minimizeToTray / minimizeOnClose on Settings screen
- Add GroupBoxes to Settings
- Add conf settings for TX Threading Limit (txthreadinglimit) and Max UI TX Limit (maxtxuilimit)
TX Threading Limit (txthreadinglimit= in .conf) - Max Transactions loaded per thread (startup)- default 4000
Max UI TX Limit (maxtxuilimit= in .conf) - Maximum Transactions loaded into the UI - default 20000
> Settings Update 

- src/chainparams.cpp
- src/qt/bitcoingui.cpp
- src/qt/transactionrecord.cpp
- src/qt/transactiontablemodel.cpp
- src/qt/transactionview.cpp
- Remove TransactionRecord::Obfuscated / related items (unused)
- Drop tab spacing to 20px from 25px (fix for smaller screens)
- Add checkpoints for 270k/275k
> Minor Fixes (Tab Spacing/Checkpoints)

- src/init.cpp
- src/main.cpp
- src/main.h
- src/miner.cpp
- src/rpc/mining.cpp
> This comes from upstream PR 12743.
> 
> * Best block hash cached for miner thread usage (preventing one of the many many cs_main locks..).
> * csBestBlock, cvBlockChange names updated to latest upstream naming convention.
from https://github.com/PIVX-Project/PIVX/pull/1203
Required for https://github.com/DAPSCoin/DAPSCoin/tree/syncing-updates
> [Upstream][Backport][Performance] Cache + guard best block hash.

- src/wallet/wallet.cpp
- src/wallet/wallet.h
> This introduces a little performance optimization, removing the double call to `GetDepthInMainChain` (ref: [#1281 (comment)](https://github.com/PIVX-Project/PIVX/pull/1281#discussion_r369861492)).
> 
> Note: in a successive PR we should review the LOCKs in this area of the wallet.
from https://github.com/PIVX-Project/PIVX/pull/1300
> [Upstream][Wallet] Add function CMerkleTx::IsInMainChainImmature

- src/masternode-sync.cpp
- src/masternode-sync.h
> Try locking cs_main when it looks for the tip, preventing possible shared resource issues.
from https://github.com/PIVX-Project/PIVX/pull/1110
> [Upstream][Masterndoes] Masternodes sync, try locking cs_main when it looks for the tip.

- src/chainparams.cpp
- src/qt/guiconstants.h
- src/qt/overviewpage.cpp
- src/qt/sendcoinsdialog.cpp
- src/qt/transactiontablemodel.cpp
- src/qt/walletmodel.cpp
- src/qt/walletmodel.h
- src/wallet/wallet.cpp
- Add OK Button to Send TX Dialog -> In case users don't want to always Copy the TX ID
- [GUI] Change colors for tx labels (colors not important here, but the logic was) (from https://github.com/PIVX-Project/PIVX/pull/677)
- Add IsLocked() return to AvailableCoins - Slightly quicker start up, less running of this function if locked
- [GUI][Model] Do not re request passphrase when the wallet is unlocked - https://github.com/PIVX-Project/PIVX/pull/1160 (adds lockForStakingOnly function, currently unused)
- [Trivial] Fix to display missing clock5.png tx image - https://github.com/PIVX-Project/PIVX/pull/847
- Checkpoints to 300k (becoming less necessary I believe, but better safe than sorry)
> Various Updates

- src/Makefile.am
- src/httpserver.cpp
- src/init.cpp
- src/main.cpp
- src/main.h
- src/miner.cpp
- src/obfuscation.cpp
- src/sync.cpp
- src/sync.h
- src/util.cpp
- src/util.h
- src/util/threadnames.cpp
- src/util/threadnames.h
- src/wallet/walletdb.cpp
> Part of a group of updates that will be doing from upstream to get up-to-date with latest sync.h/cpp sources.
> 
> This first PR involves:
> 
> * sync.h/cpp code refactor + reorg.
> * threadnames.h/cpp file creation + connection (where "connection" means that all of the previous `RenameThread` method calls where modified to use the new `util::ThreadRename` method).
from https://github.com/PIVX-Project/PIVX/pull/1335
There is a 2nd and 3rd part but they have not been merged yet.
> [Upstream] Inlining sync.cpp with latest upstream, first step. 

- src/chainparams.cpp
- src/chainparams.h
- src/chainparamsbase.cpp
- src/chainparamsbase.h
- src/test/base58_tests.cpp
- src/test/test_dapscoin.cpp
- src/test/wallet_tests.cpp
- src/wallet/test/wallet_tests.cpp
> This network is un-necessary as our unit test suite can simply be run
> with MainNet's parameters, which is basically what we already do.
> 
https://github.com/PIVX-Project/PIVX/pull/1330
> [Upstream][Cleanup] Remove stale UNITTEST network

- src/Makefile.am
- src/main.cpp
- src/rpc/rawtransaction.cpp
- src/sync.cpp
- src/sync.h
- src/util/macros.h
> ... Effort to bring us up-to-date with upstream's sync.h/cpp sources.
> 
> The only task that left to be fully up-to-date with upstream, that will leave for a third PR because it touches other areas of the sources and want to keep this as small as possible, is the `CCriticalSection` removal and replacement with the `RecursiveMutex` typedef.
https://github.com/PIVX-Project/PIVX/pull/1336
> [Upstream] Sync Upgrades, part 2.

- src/qt/addresstablemodel.cpp
- src/qt/bantablemodel.cpp
- src/qt/paymentserver.cpp
- src/qt/peertablemodel.cpp
- src/qt/recentrequeststablemodel.cpp
- src/qt/transactiontablemodel.cpp
> `qSort`, `qStableSort`, `qLowerBound`, and `qUpperBound` have been
> marked as deprecated since Qt 5.2.
> 
> Also, `QSslSocket::setDefaultCaCertificates()` and `QSslSocket::systemCaCertificates()`
> member functions are obsolete as of Qt 5.12
> 
> This PR replaces the former with their `std::` equivalents, and the latter
> with `QSslConfiguration` equivalents.
> 
> Changes maintain backwards compatibility with Qt 5.5.1
from https://github.com/PIVX-Project/PIVX/pull/1357
> [Upstream] [Qt] Replace deprecated Qt methods

- src/init.cpp
- src/main.cpp
- src/main.h
- src/wallet/wallet.cpp
- src/wallet/wallet.h
> Straightforward.
from https://github.com/PIVX-Project/PIVX/pull/1366
It was closed as they no longer support Reserve Balance. We still do, so this makes sense.
> [Upstream][Refactor] move nReserveBalance from main to wallet

- src/init.cpp
> Backport of [bitcoin#7257](https://github.com/bitcoin/bitcoin/pull/7257)
> 
> Adds helper methods for common translatable string outputs during init, end result is that the number of strings sent to Transifex is reduced/standardized.
from https://github.com/PIVX-Project/PIVX/pull/1376
> [Upstream][Init] Combine common error strings so translations can be shared

- src/checkpoints.cpp
- src/checkpoints.h
- src/main.cpp
- src/qt/clientmodel.cpp
- src/qt/clientmodel.h
first commit was required for GuessVerificationProgress const and is from: https://github.com/PIVX-Project/PIVX/commit/80753f9bf591367960f8a71d788633dde1c3a3ac
> **Probelm**: GUI client model requires calls to `chainActive` (thus locking the main UI thread) for the following functions:
> 
> * getNumBlocks
> * getLastBlockDate
> * getLastBlockHash
> * getVerificationProgress
> 
> **Fix**: use the `NotifyBlockTip` core signal to update a cached tip blockindex in `BlockTipChanged`, and rely on this object for the aforementioned functions.
> 
from https://github.com/PIVX-Project/PIVX/pull/1408
> [Upstream][GUI][Model] Save cache BlockIndex tip in the model

- src/qt/bitcoingui.cpp
- src/qt/forms/overviewpage.ui
- src/qt/overviewpage.cpp
With #116  we are able to add better status info to Network Status and Overview, screenshots below:
- Add "Loading Blocks" status text
- Add "(loading)" to sync circle on Overview page
> [GUI] "Loading Blocks" statuses added to Network Status and Overview

- src/Makefile.test.include
- src/net.cpp
- src/net.h
- src/test/net_tests.cpp
> backport of https://github.com/bitcoin/bitcoin/pull/7696/files
> 
> * CAddrDB modified so that when de-serialization code throws an exception Addrman is reset to a clean state
> * CAddrDB modified to make unit tests possible
> * Regression test created to ensure bug is fixed
> * StartNode modifed to clear adrman if CAddrDB::Read returns an error code.
from https://github.com/PIVX-Project/PIVX/pull/1378
> [Upstream][Net] Fix de-serialization bug where AddrMan is corrupted after exception

- src/rpc/masternode.cpp
> `masternodecurrent` RPC is improperly returning the masternode with rank 1 instead of the next winner.
> Closes #1348
> 
> ```
> > getblockcount
> 2236241
> 
> > masternodecurrent
> {
>   "protocol": 70918,
>   "txhash": "cfa69f018741e0960a436788391d9d2cec0f9aceed30e883a78818f7c073fba1",
>   "pubkey": "DHeEycDFe9pWr3FahcnTbavy8Urb1832HU",
>   "lastseen": 1583439177,
>   "activeseconds": 6690804
> }
> 
> > getmasternodewinners 0
> [
>   {
>     "nHeight": 2236242,
>     "winner": {
>       "address": "DHeEycDFe9pWr3FahcnTbavy8Urb1832HU",
>       "nVotes": 10
>     }
>   },
>   ...
> ]
> ```
> 
> https://explorer.pivx.link/block/9fe33eedf5f61a8e9f8d50b9007c25d1b0260f0c97f88265feda4c06dfa86725
> 
> Note: `GetCurrentMasterNode` returns the masternode with lower rank and it's used as winner …
> [Upstream][RPC][Bug] Fix masternodecurrent: return next winner, not rank-1 mn

- src/qt/forms/rpcconsole.ui
For some reason the text of these items were not able to be selected. This fixes this minor issue. Useful if the user wants to copy/paste the Data directory or last block hash for troubleshooting or other tasks.
> [UI] Make "Data Directory" and "Last block hash" details selectable

- src/main.cpp
- src/net.h
> Straightforward back port. Sets a max block locator entries size.
> 
> Coming from [upstream@13907](https://github.com/bitcoin/bitcoin/pull/13907/commits).
from https://github.com/PIVX-Project/PIVX/pull/1367
> [Upstream][Net] Max block locator entries size.

- src/qt/winshutdownmonitor.cpp
Removes the "GUI: $registerShutdownBlockReason: Successfully registered: DAPS didn$t yet exit safely...$" line from debug.log and outputs it to qDebug instead
> [Trivial] Replace qWarning() with qDebug() for cleaner debug.log (Windows only)

- src/Makefile.qt.include
- src/qt/bitcoingui.cpp
- src/qt/bitcoingui.h
- src/qt/clientmodel.cpp
- src/qt/clientmodel.h
- src/qt/dapscoin.qrc
> Tor Icon is displayed when the client is initialized with a successful
> tor service connection.
> 
> Icon is hidden otherwise.
> 
This is prep for future Tor/Proxy support being restored. (Currently settings are just not displayed so cannot be used).
from https://github.com/PIVX-Project/PIVX/pull/626
> [Upstream][Qt] Add Tor service icon to status bar

- src/qt/overviewpage.cpp
- src/qt/overviewpage.h
- Code cleanup, removing an extra TRY_LOCK, unused variables, and an unneeded function.
- Changes the "0 of BlockTotal" to "??? of BlockTotal" on Overview screen syncing circle
> [Cleanup][UI] Overview Changes

- src/init.cpp
- src/net.cpp
- src/net.h
- src/netbase.cpp
> If a timeout happens while reading the proxy response, this effectively means we timed out while connecting to the remote node. This is very common for Tor, so do not print an error message to the log in that case.
> 
> Avoids a flood of
> 
> ```
> ERROR: Error reading proxy response
> ```
> 
> while running through Tor, causing users to blame the proxy.
> 
> Coming from upstream [9726](https://github.com/bitcoin/bitcoin/pull/9726)
from https://github.com/PIVX-Project/PIVX/pull/1460
> [Upstream] netbase: Do not print an error on connection timeouts through proxy

- src/init.cpp
> `g_best_block` holds a cached best block hash.
> This is updated during `ActivateBestChain` (in `UpdateTip`).
> 
> **Problem**: at startup, the object is not initialized until a new block arrives (`ActivateBestChainStep` is not called) thus `g_best_block != chainActive.Tip()->GetBlockHash()` so, if the client stakes before receiving a new block, that stake gets orphaned.
> In case of segregated devnet with just one staker, it is impossible to move the chain at all.
from https://github.com/PIVX-Project/PIVX/pull/1457
> [Upstream][Bug] Fix g_best_block_initialization in ABC

- src/chainparams.cpp
- src/chainparams.h
- src/net.cpp
> Backport of [bitcoin#8083](https://github.com/bitcoin/bitcoin/pull/8083)
> 
> This adds the ability to filter DNS seed requests by service bit, but does not actually implement any filtering other than the default `NODE_NETWORK` (for now). Further related upstream backports will follow.
from https://github.com/PIVX-Project/PIVX/pull/1452
> [Upstream][Net] Add support for dnsseeds with option to filter by servicebits

- src/qt/clientmodel.cpp
- src/qt/clientmodel.h
> We were locking `cs_main`, calling `IsInitialBlockDownload` on every new row inserted in the transaction table model.
> 
> This PR caches the IBD state and updates it on every new block from the back-end without lock `cs_main` at all.
from https://github.com/PIVX-Project/PIVX/pull/1468
> [Upstream][GUI] Less GUI locks, IBD state cached..

- depends/packages/openssl.mk
> The URL for OpenSSL 1.0.1k has changed, so update it here.
from https://github.com/PIVX-Project/PIVX/pull/1483
> [Upstream][Depends] Update OpenSSL download URL

- src/qt/clientmodel.cpp
- src/qt/clientmodel.h
> Fixing cacheTip not sync with the back-end information when the node has no connection and thereby there was no tip signal broadcasted to the front-end to update the cached tip. Showing a wrong chain height instead of the correct back-end tip.
> 
> This will only happen one time. Once the tip gets updated, it will not request it anymore from the back-end and only receive signals. Not locking `cs_main` anymore.
from https://github.com/PIVX-Project/PIVX/pull/1487
> [Upstream][GUI] ClientModel try to initialize cacheTip if it's null.

- src/net.h
> This fixes the getaddr response which is crucial for dns-seeders and wallet to find peers.On current code it only checks localhost addr being valid and if its known,while in reality we need to relay the node passed in args.
> 
> Credit to @Aviator-Coding for pointing the bug out and the fix.
from https://github.com/PIVX-Project/PIVX/pull/1492
> [Upstream][Net] Relay actual peers instead of localhost on getaddr

- src/qt/clientmodel.cpp
> Previously, we were updating the MNs cached count in the GUI every 4 seconds and there is absolutely no need to try to lock the important `cs_main` for a number so rarely used like the masternodes count. 40 seconds looks more like a decent time to check for MNs updates.
> 
> Maybe we should discuss in the future if we really want to continue polling for this number. Could move it to a signal but still, it's a rarely used number. Thinking that it would be just fine to update it when the user request it and done.
from https://github.com/PIVX-Project/PIVX/pull/1501
> [Upstream][GUI] Update MNs GUI count every 40 seconds.

- src/qt/bitcoingui.cpp
- src/qt/clientmodel.cpp
- src/qt/clientmodel.h
- src/qt/overviewpage.cpp
Instead of locking cs_main with IsInitialBlockDownload() we've switched to clientModel->inInitialBlockDownload() due to changes allowed by #133/#137
Also, remove the (loading) text added on overview as a temp fix to eliminate user confusion.\
Some users in the test group thought they had lost their chain data due to the 0 being shown - this is no longer displayed. The loading statuses may be introduced at a later date but more informatively and to match in all area (ie. Network Status blocks status of syncing/synced should show the same as Overview - currently block count is shown but not if synced/syncing for easier access to this information without changing tabs.)
> [UI] Less Freezing (pt. 1)

- src/qt/peertablemodel.cpp
> Fixes #13483
> 
> The address in the network peer table is prefixed with an up-arrow symbolizing an outbound connection, or an down-array symbolizing an inbound connection. See screenshot.
> 
> The user has an easy visual confirmation about the connection direction state. I really like it :)
> Impact to columns sorting is grouping by inbound/outbound first, which in my opinion is an advantage, too.
> ![bildschirmfoto](https://user-images.githubusercontent.com/8447873/41862752-13803eb2-78a5-11e8-9126-a52385f5ec19.png)
from https://github.com/bitcoin/bitcoin/pull/13537
> [Upstream] GUI: Peer table: Visualize inbound/outbound state for every row

- build-aux/m4/ax_boost_base.m4
- build-aux/m4/ax_boost_system.m4
- depends/packages/boost.mk
> Version [1.70](https://www.boost.org/users/history/version_1_70_0.html) is most recent.
> 
> Versions needed for:
> 
> * 1.66: #12557: fixes the single arm64 configuration ([06ee5b5](https://github.com/ruslo/hunter/commit/06ee5b54ef310b376cdaa7928f89b4995ceb2efc))
https://github.com/bitcoin/bitcoin/pull/15461
> [Upstream] [Depends] update to Boost 1.70

- src/init.cpp
> Trivial change, remove the PID file once the shutdown process is completed.
from https://github.com/PIVX-Project/PIVX/pull/1517
> [Upstream] Shutdown: remove PID file at the very end.

- src/qt/dapscoin.cpp
> Default `-printtoconsole` to false for the GUI.
> 
> GUI programs should not print to the console unnecessarily. For example, when launched by the
> window manager, the output might end up in the X session log file, resulting in duplicate logging. On Windows, it is pointless as well because pivx-qt isn't a console application.
> 
> Coming from upstream@[13055](https://github.com/bitcoin/bitcoin/pull/13055)
from https://github.com/PIVX-Project/PIVX/pull/1530
> [Upstream] [GUI] Don't log to console by default. 

- depends/packages/qt.mk
> While looking at #16838 I found at least two cases of `sed` patching in depends that now seems to be redundant. There's possibly a [third case](https://github.com/bitcoin/bitcoin/pull/16837#discussion_r322842701), but I haven't looked into that enough yet.
> 
> Patching `0` -> `kCGMouseButtonLeft` should not be required, as [`kCGMouseButtonLeft`](https://code.qt.io/cgit/qt/qtbase.git/tree/src/plugins/platforms/cocoa/qcocoacursor.mm?h=5.9#n82) has been used in the `cocoa/qcocoacursor.mm` source for a while.
> 
> The include we were modifying in [`src/plugins/platforms/xcb/qxcbxsettings.cpp`](https://code.qt.io/cgit/qt/qtbase.git/tree/src/plugins/platforms/xcb/qxcbxsettings.cpp?h=5.9#n47) was removed in [this commit](https://code.qt.io/cgit/qt/qtbase.git/commit/src/plugins/platforms/xcb/qx …
> [Upstream] build: remove redundant sed patching

- src/qt/coincontroldialog.cpp
- src/qt/coincontroldialog.h
> Prioritize the action described by the button:
> 
> * if "Select All", then verify that all entries are checked, otherwise check them
> * if "Unselect All", then verify that all entries are unchecked, otherwise uncheck them.
> 
> Closes #1592
> 
> **Note**: if we had just prioritized `Qt::Unchecked` at the beginning, instead of `Qt::Checked`, without taking into account the status/text of the button, we would have solved 1592, but we'd have another bug where, using first "Select All" to check all entries, and then manually deselecting some entry, results in a successive "Unselect All" still behaving like "Select All".
from https://github.com/PIVX-Project/PIVX/pull/1595
[for when we restore Coin Control]
> [Upstream] [GUI][Bug] Fix "Select all" / "Unselect all" logic in coincontrol

- src/init.cpp
- src/net.cpp
Otherwise it just responds to this obvious bit of configuration by trying to connect to "0" in a loop.
Coming from upstream@515e2642eb45bda56156b1213b25fb4886d3fdbe
from https://github.com/PIVX-Project/PIVX/pull/1533
> [Upstream] [Backport] Make connect=0 disable automatic outbound connections. 

- src/keystore.cpp
- src/keystore.h
- src/qt/coincontroldialog.cpp
- src/qt/coincontroldialog.h
- src/qt/walletmodel.cpp
- src/qt/walletmodel.h
- src/wallet/wallet.cpp
- src/wallet/wallet.h
- src/wallet/wallet_ismine.cpp
- src/wallet/wallet_ismine.h
- src/wallet/walletdb.cpp
> Remove the backend code which was added (in #278) to support the management of multisig addresses via GUI. Since our current GUI no longer has this feature, this code is currently disconnected and, therefore, can be cleaned up.
> 
> If we ever decide to re-add a GUI tool for multisig addresses, we can re-implement it properly.
from https://github.com/PIVX-Project/PIVX/pull/1662
> [Upstream] [Cleanup] Remove obsolete multisig code

- src/chainparams.cpp
Many nodes seem to have got stuck on block 458732, with this log:
> ERROR: AcceptBlock : prev block 51d7f917147f3bec3f2e6767fd70c14730a0b0773a7b967e827336e936cf50e2 is invalid, unable to add block 35ff8e3884036187ed56e7d4a4adda3e0f75eac5655afd4cef8605954b28362f
so we checkpoint both 458733 and 458734
> Add checkpoints for blocks 458733/458734

- src/masternode.h
Removes un-used function SliceHash (which is also buggy and overflowing,
trying to copy 64 bytes to a destination buffer having only 8 bytes).
from https://github.com/PIVX-Project/PIVX/pull/1513
> [Upstream] [Trivial] Remove CMasternode::SliceHash

- src/qt/sendcoinsdialog.cpp
- src/wallet/wallet.cpp
- Update "Transaction Size Too Large" msgbox
- Add additional error msgbox as the one in catch was not displaying (failed sweeping transaction)
- Update text for work around UTXO limit msgbox
- Updated logging for sweeping transactions
> Logging/Error MsgBoxes

- src/qt/sendcoinsdialog.cpp
Add error MsgBox when attempting to send a transaction before synced
"Sending DAPS is disabled when you are still syncing the wallet. Please allow the wallet to fully sync before attempting to send a transaction."
> [UI] Add error MsgBox when attempting to send a transaction before synced

- src/Makefile.am
- src/allocators.h
- src/base58.cpp
- src/crypter.cpp
- src/crypter.h
- src/qt/paymentrequestplus.cpp
- src/qt/paymentrequestplus.h
- src/qt/paymentserver.cpp
- src/random.cpp
- src/streams.h
- src/support/cleanse.cpp
- src/support/cleanse.h
- src/util.cpp
- src/utilstrencodings.cpp
- src/wallet/db.cpp
> Backport of [bitcoin#5689](https://github.com/bitcoin/bitcoin/pull/5689) and [bitcoin#11196](https://github.com/bitcoin/bitcoin/pull/11196). That's part of the project of keeping up with Bitcoin Core and moving away from OpenSSL as much as possible.
from https://github.com/PIVX-Project/PIVX/pull/761
> [Upstream] [Refactoring] Abstract out and switch openssl cleanse

- src/main.cpp
> Straightforward, coming from [btc@8007](https://github.com/bitcoin/bitcoin/pull/8007)
Optimistically test the latch bool before taking the lock.
For all IsInitialBlockDownload calls after the first to return false,
this avoids the need to lock cs_main.
from https://github.com/PIVX-Project/PIVX/pull/1728
Coming from btc@f0fdda0181e1b05b66541bf235c6702c41664170
> [Upstream] IsInitialBlockDownload: usually avoid locking

- depends/packages/libevent.mk
- depends/patches/libevent/0001-fix-windows-getaddrinfo.patch
> TLDR: This poaches a commit from #18287 and adds one more to adjust the Windows version targeted when building libevent. These changes combined should fully fix ipv6 usage with the RPC server on Windows.
> 
> Binding the RPC server to a ipv6 address does not currently work on Windows.
> We currently try and bind to `127.0.0.1` and `::1` [by default](https://github.com/bitcoin/bitcoin/blob/master/src/httpserver.cpp#L304).
> 
> On Windows you'll see lines like this in debug.log:
> 
> ```shell
> 2020-06-24T01:49:04Z libevent: getaddrinfo: nodename nor servname provided, or not known
> 2020-06-24T01:49:04Z Binding RPC on address ::1 port 8332 failed
> ```
> 
> This issue was bought up in, and supposedly fixed by #18287, however the two people that tested it, both said that it didn't fix the …
> [Upstream] build: target Windows 7 when building libevent and fix ipv6 usage

- src/leveldbwrapper.cpp
> The `leveldb::Status` class logs the filename of corrupted files, which might be useful when looking at error reports from usres. In theory this is already logged via the `LogPrintf()` statement in `HandleError()`, but that may not always be close to where the final error message is logged, e.g. see [#11355 (comment)](https://github.com/bitcoin/bitcoin/issues/11355#issuecomment-340340542) where the log trace provided by the user does not contain that information (and other user comments in the same issue).
> 
> This also adds a log message instructing the user to run the process with `-debug=leveldb`, which provides much more verbose error messages about LevelDB internals. This may not really help much, but improving the error messages here can't hurt.
from …
> [Upstream] Improve Fatal LevelDB Log Messages

- src/net.cpp
- src/net.h
- src/qt/rpcconsole.cpp
> Rather than doing a circle and re-resolving the node's IP, just use the one from nodestats directly.
> 
> This requires syncing the addr field from CNode.
> 
> Fixes #8876
from https://github.com/bitcoin/bitcoin/pull/8885
This bug was introduced with #151 - here we use a slightly modified version of https://github.com/bitcoin/bitcoin/commit/cb78c60534e5be205f9190cb0cde700f9e9fa38d as we do not have conman)
> [Upstream] gui: fix ban from qt console

- .travis.yml
- contrib/gitian-build.sh
- contrib/gitian-descriptors/gitian-osx.yml
- contrib/macdeploy/README.md
- depends/hosts/darwin.mk
- depends/packages/native_cctools.mk
- depends/packages/qt.mk
- depends/patches/qt/mac-qmake.conf
- doc/README_osx.md
- doc/build-osx.md
> TLDR: This updates our macOS toolchain to use a newer version of Clang, cctools (including new [dependency on libtapi](https://github.com/tpoechtrager/cctools-port/tree/master#dependencies)), LD64 and the macOS SDK.
> 
> I've been testing depends builds (`HOST=x86_64-apple-darwin16`) inside a Debian Buster [Docker container](https://github.com/fanquake/core-review/blob/master/docker/debian.dockerfile), and running the resultant `bitcoind` and `bitcoin-qt` binaries on a macOS `10.14.4` system. The `.dmg` generated by a `make deploy` also mounts correctly on the same macOS system.
> 
> #### Clang
> Upgraded from `3.7.1` to [`6.0.1`](https://releases.llvm.org/6.0.1/docs/ReleaseNotes.html)
> 
> #### cctools
> * cctools `877.8` -> [`921`](https://opensource.apple.com/tarballs/cctools/)
> * …
> [Upstream] build: macOS toolchain update

- src/qt/walletmodel.cpp
- src/qt/walletmodel.h
> When syncing or reindexing with a pre-existing wallet, there is no need
> to do any updating of the transaction table model data when the chain's
> tip time is prior to the wallet's creation time.
> 
> This offers a scaling performance boost as the number of transactions
> a wallet has increases. For context, here are some sync time comparisons:
> 
> Current `master`:
> 
> ```
> Time to sync to Nov 27 2019: ~4 hours
> ```
> 
> This PR:
> 
> ```
> Time to sync to Nov 27 2019: ~1 hour 30 minutes
> ```
> 
> The wallet is a testnet wallet created on Nov 27 2019, and has roughly
> 96k transactions since then. Sync time from wallet creation timestamp
> to the current block height remain unchanged here.
> 
> Note: wallets that have **imported** a watch-only address, a private key,
> or set a …
> [Upstream] [GUI] Return early in pollBalanceChanged

- src/main.cpp
> As the title says, the wallet shouldn't resend transactions if the node is importing or in IBD state. The node doesn't know the real status until it's synced.
from https://github.com/PIVX-Project/PIVX/pull/1783
> [Upstream] [Wallet] Do not try to resend transactions if the node is importing or in IBD

- src/qt/clientmodel.cpp
- src/qt/clientmodel.h
- src/qt/rpcconsole.cpp
> The masternodes polling was starting when the clientModel object is generated, locking `cs_main` every certain amount of time without care on whether the information is being presented or not.
> This PR changes it, the polling timer will only be started when the information is needed on the screen and stopped when the user leaves such screen.
from https://github.com/PIVX-Project/PIVX/pull/1782
> [Upstream] [GUI] Start masternodes polling timer only when is needed.

- src/wallet/wallet.cpp
Copy of #207 but to `master` for this release
> [BUG] fValid fix - If wallet is locked, return false on generateKeyImage

- src/net.cpp
- src/net.h
- src/qt/rpcconsole.cpp
Rather than doing a circle and re-resolving the node's IP, just use the one
from nodestats directly.
This requires syncing the addr field from CNode.
(slightly modified version of https://github.com/bitcoin/bitcoin/pull/8885/commits/cb78c60534e5be205f9190cb0cde700f9e9fa38d as we do not have conman)
Duplicate of #211 to master for this release
> [BUG] gui: fix ban from qt console

- src/main.cpp
- src/net.cpp
- src/net.h
- Add IsUnsupportedVersion for banned versions
Returns:
- /DAPScoin:0.27.5.1/
- /DAPScoin:1.0.0/
- /DAPScoin:1.0.1/
- /DAPS:1.0.1.3/
- /DAPS:1.0.2/
- /DAPS:1.0.3.4/
- /DAPS:1.0.4.6/
- /DAPS:1.0.5.7/
- /DAPS:1.0.5.8/
Update log text for IsUnsupportedVersion -> better match other wording used in logs and describe actions in proper order
> Add IsUnsupportedVersion for banned versions

- src/qt/optionspage.cpp
Since a user is technically not able to successfully stake until the wallet is fully synced, prevent toggling it on by adding a check for synced
> Add check for synced before allowing Staking toggle

- src/wallet/rpcwallet.cpp
Change RPC for showing stealth address to only return the address
Affects:
showstealthaddress
getstealthaddress
getaccountaddress
Before:
showstealthaddress
`stealthaddress: Address`
After:
showstealthaddress
`Address`
> [RPC] Change RPC for showing stealth address to only return the address

- src/net.cpp
This is a requirement for the PoA Fix
- Set date of Tuesday, December 1, 2020 12:00:00 AM (GMT) for banning to begin
> Ban All Previous Versions

- .travis.yml
- Makefile.am
- build-aux/m4/ax_boost_program_options.m4
- build-aux/m4/ax_check_compile_flag.m4
- build-aux/m4/ax_check_link_flag.m4
- build-aux/m4/ax_check_preproc_flag.m4
- build-aux/m4/ax_cxx_compile_stdcxx.m4
- build-aux/m4/ax_gcc_func_attribute.m4
- build-aux/m4/ax_pthread.m4
- build-aux/m4/bitcoin_find_bdb48.m4
- build-aux/m4/bitcoin_subdir_to_include.m4
- configure.ac
- contrib/macdeploy/macdeployqtplus
- depends/config.site.in
- share/qt/Info.plist.in
- src/Makefile.am
- src/Makefile.qt.include
- src/Makefile.qttest.include
- src/Makefile.test.include
- src/compat.h
- src/compat/strnlen.cpp
- src/hash.h
- src/protocol.cpp
Part 1 of many to bring updates to the build system that were missed previously.
(travis commit is not used, but kept for completeness - we will be using GitHub Actions in the future)
> This is an extension of #532, and while testing can be done on this prior to the merging of #532, this PR should not be merged first.
> 
> Below is what has been updated here:
> 
> * [x]  Update the various m4 definition files
> * [x]  Fixup a couple Variable Length Array (`-Wvla`) errors in `src/hash.h`
> * [x]  Wrap the `strnlen()` define and implementation in a precompiler conditional
> * [x]  Reduce the instances where client version numbers are defined
> * [x]  Switch to the semi-new `minimal` TravisCI image
> 
> Of particular note in this update is the new configure option `--enable-werror` which can …
> [Upstream] [Build] Update build system from upstream

- src/poa.cpp
Fix PoA warning - re: '&&' within '||'
```poa.cpp:251:81: warning: '&&' within '||' [-Wlogical-op-parentheses]
if (!pIndexLoop || pIndexLoop->GetBlockHash() != lastAuditedPoSHash && !IsFixedAudit(fixedPoSAuditedHash.GetHex())) {
~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
poa.cpp:251:81: note: place parentheses around the '&&' expression to silence this warning
if (!pIndexLoop || pIndexLoop->GetBlockHash() != lastAuditedPoSHash && !IsFixedAudit(fixedPoSAuditedHash.GetHex())) {
^
(                                                                                              )
1 warning generated.```
> [Build] Fix PoA warning - re: '&&' within '||'

- .github/workflows/daps-build-factory.yml
Adding GitHub Action Script to build for all our currently supported OSs.
Tests disabled as those are still broken and require a cleanup which will be in a separate PR.
Based on the one from https://github.com/Veil-Project/veil/blob/master/.github/workflows/build-factory.yml
Running here: https://github.com/DAPSCoin/DAPSCoin/actions/runs/414063001
> [Build] Add GitHub Action Script

- src/init.cpp
- src/qt/walletmodel.cpp
- src/qt/walletmodel.h
- src/qt/walletview.cpp
- src/wallet/wallet.cpp
- src/wallet/wallet.h
- src/wallet/walletdb.cpp
- src/wallet/walletdb.h
Cherry pick as it is useful for us:
from https://github.com/PIVX-Project/PIVX/pull/582/commits/8046a528a053fd7d792cbe893a7b158d6c9bced8
Adding:
- init option : -backuppath=<(dir/file)>", _("Specify custom backup path to add a copy of any wallet backup. If set as dir, every backup generates a timestamped file. If set as file, will rewrite to that file every backup.
- backupwallet RPC command
> [Upstream] custom wallet backup paths

- src/qt/forms/optionspage.ui
- src/qt/optionspage.cpp
- src/qt/optionspage.h
- src/qt/sendcoinsdialog.cpp
As requested by a few community members, added a feature to request 2FA code before each transaction send.
Settings screen:
Send Confirmation:
2FA Request:
> [Feature] Add fAlwaysRequest2FA to request 2FA before each send

- src/poa.cpp
CheckPoAContainRecentHash checks previous PoA block, so we use 719456 here
> [Fix] Add sync fix for block 803585
